spring:
  security:
    oauth2:
      client:
        registration:
          linkedin:
            clientSecret: <your-client-secret>
            provider: linkedin
            client-name: Linkedin
            clientId: <your-client-id>
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: r_liteprofile, r_emailaddress
            client-authentication-method: post
          facebook:
            clientSecret: <your-client-secret>
            clientId: <your-client-id>
          github:
            clientSecret: <your-client-secret>
            clientId: <your-client-id>
          google:
            clientId: 613394712795-r40flit5sb9hj4s1uhniuvk7s7eenjd0.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/me
            user-name-attribute: id
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/medical
    username: postgres
    password: password
app:
  cors:
    allowedOrigins: http://localhost:4200,http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris: http://localhost:4200/oauth2/redirect,http://localhost:8081/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect
  auth:
    tokenExpirationMsec: '864000000'
    tokenSecret: 04ca067b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
linkedin:
  email-address-uri: https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))

loggin:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: TRACE
        type: TRACE