name: Heroku Deployment
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          docker_compose_file: 'docker-compose.yml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"medical-app","appname":"medicalme","apptype":"web"},{"imagename":"dbpostgresql","appname":"medicalme-db","apptype":"worker"}]' # List of Docker Image name, Heroku app and Heroku app type